### ISSUE TITLE
CJK language support

### ISSUE THREAD

**Issue by abeq** [fathyb/html2svg#12]
Hi, 
It seems great for site with English. Will it be able to work for CJK Language as well?

**Comment by fathyb** [comment]
I've just released full unicode support! You can pull it on the latest Docker image: `docker pull fathyb/html2svg`. Here are some SVG examples:

![wiki ar](https://user-images.githubusercontent.com/5746414/202543110-583a782e-705f-4987-8350-b60b16f6213f.svg)
![wiki zh](https://user-images.githubusercontent.com/5746414/202543121-cb0a1a6c-b80e-4829-8977-ee38c8230bb9.svg)
![wiki ja](https://user-images.githubusercontent.com/5746414/202543129-301850a7-58a0-40c0-a1e0-f60ea6fd22e7.svg)
![wiki ko](https://user-images.githubusercontent.com/5746414/202543141-03de6f44-d03f-4471-a65e-e98c686506e0.svg)
