### ISSUE TITLE
Feature request: target viewport size

### ISSUE THREAD

**Issue by prurigro** [fathyb/html2svg#14]
It'd be great if it was possible to create exports of mobile sites in addition to desktop.

This project is awesome btw, thanks for creating it!

**Comment by fathyb** [comment]
I added new `--width` and `--height` options to set the viewport size, here's an example:
```console
$ docker run fathyb/html2svg https://mui.com --width 500 > mui.svg
```

You can pull it on the latest Docker image!

**Comment by prurigro** [comment]
Amazing, thanks so much!
