### ISSUE TITLE
Feature Request: Full scroll

### ISSUE THREAD

**Issue by prurigro** [fathyb/html2svg#17]
This might be too complex to reasonably include and maintain as a feature, but for the purpose of outputting website previews it would be handy if it was possible to capture the full viewport (maybe as a flag like `--height full` or `--height auto` or something?).

Maybe it could detect the body element's height and then set the viewport height to match that before taking a snapshot?

**Comment by fathyb** [comment]
You should be able to do that with the `--full` option! Going to update the readme to include it in a bit..

**Comment by prurigro** [comment]
Amazing, it seems like you've thought of everything! Thanks again for the awesome tool :)
