### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by fathyb** [fathyb/html2svg#3]
Tracking PDF support here

**Comment by seanghay** [comment]
PNG/JPEG supports as well please.

**Comment by DeanWard** [comment]
wkhtmltopdf already exists for this purpose - https://wkhtmltopdf.org/

**Comment by gbtb** [comment]
> wkhtmltopdf already exists for this purpose - https://wkhtmltopdf.org/

Core browser engine inside wkhtmltopdf is severely outdated. Flexbox and everything that came after it is not supported. Nevertheless, wkhtmltopdf could be used as a baseline for features to implement. Also compatible CLI could be developed which would ease the transition for end users.

**Comment by fathyb** [comment]
PDF support has landed! You can try it on the latest Docker image:
```console
docker run fathyb/html2svg https://google.com --format pdf > google.pdf
```

Tracking the raster support (JPEG, PNG, WebP) on #9.
